language: python
python:
  - "3.7"
install:
  - pip install pipenv
  - pipenv install
#   - pip install -r requirements.txt
# command to run tests
script:
  - invoke initialize
  - invoke security
  - invoke lint
  - invoke unit
